### ISSUE TITLE
etcd.sh should not rely on external tools

### ISSUE THREAD

**Issue by palonsoro** [peterducai/openshift-etcd-suite#1]
It would be more optimal if `etcd.sh` did not depend on either `omc` or `omg` or any other external tool. As long as the goal is to check on etcd logs and must-gathers and oc adm inspects have a well-known structure, it should be possible to read the files from there (for reference, on `${MUST_GATHER_ROOT}/namespaces/openshift-etcd/pods/...` folders).

**Comment by peterducai** [comment]
latest version use only local tools (grep, awk, cut..)
