### ISSUE TITLE
Escape the dollar sign in help_etcd_objects()

### ISSUE THREAD

**Issue by troudbal** [peterducai/openshift-etcd-suite#7]
The dollar sign should be escaped on this line
https://github.com/peterducai/openshift-etcd-suite/blob/2592de190d85abb2d47c61328bc13928e08ecd07/etcd.sh#L54
otherwise the shown awk command is incorrect:
```
...
List secrets per namespace:

> oc get secrets -A --no-headers | awk '{ns[]++}END{for (i in ns) print i,ns[i]}'
...
```

**Comment by peterducai** [comment]
fixed in [54ab485](https://github.com/peterducai/openshift-etcd-suite/commit/54ab48561bbd367d051ea59128ffa3ae7df69614)
